In [1]:
import numpy as np

A=np.array([1,2,3,4])
A

array([1, 2, 3, 4])

In [2]:
B=np.array( [[1,2],[3,4]])
B

array([[1, 2],
       [3, 4]])

In [3]:
A.shape
B.shape

(2, 2)

In [4]:
A.shape

(4,)

In [6]:
A.reshape(1,4)

array([[1, 2, 3, 4]])

In [8]:
A.reshape(1,4).shape

(1, 4)

In [9]:
A.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
A.reshape(4,1).shape

(4, 1)

In [13]:
np.random.rand(3,2)

array([[0.84511734, 0.97991839],
       [0.33610137, 0.95714963],
       [0.83772427, 0.95619254]])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.ones_like(A)

array([1, 1, 1, 1])

In [16]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.zeros_like(A)

array([0, 0, 0, 0])

In [19]:
np.full((3,2),10)

array([[10, 10],
       [10, 10],
       [10, 10]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
import numpy as np

np.random.seed(12)

A=np.random.randint(0,9,4).reshape(2,2)
B=np.random.randint(0,9,4).reshape(2,2)+1

A


array([[6, 1],
       [2, 3]])

In [23]:
B

array([[4, 1],
       [7, 2]])

In [24]:
A

array([[6, 1],
       [2, 3]])

In [25]:
A

array([[6, 1],
       [2, 3]])

In [26]:
B

array([[4, 1],
       [7, 2]])

In [27]:
A/B

array([[1.5       , 1.        ],
       [0.28571429, 1.5       ]])

In [28]:
import numpy as np

A=np.arange(1,7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
import numpy as np

A=np.arange(1,13).reshape(2,2,-1)

In [31]:
A

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
A.T

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [36]:
import numpy as np
A=np.arange(1,13).reshape(2,2,-1)
A.transpose(1,0,2)

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [37]:
import numpy as np
A=np.arange(30).reshape(5,6)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
A[0,2]

2

In [39]:
A[2,3]

15

In [40]:
A[:,0::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [41]:
A[:::,0:::]

SyntaxError: invalid syntax (<ipython-input-41-1f617b3355a0>, line 1)

In [42]:
A[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
A[:,0::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [46]:
np.array([A[0,1],A[1,2],A[2,3],A[3,1],A[4,0]])

array([ 1,  8, 15, 19, 24])

In [47]:
A[[0,1,2,3,4],[1,2,3,1,0]]

array([ 1,  8, 15, 19, 24])

In [48]:
A.>20

SyntaxError: invalid syntax (<ipython-input-48-843bdadf9742>, line 1)

In [49]:
A>20

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [50]:
A[A>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
import numpy as np

A=np.array([1,2,3])

In [52]:
A*2

array([2, 4, 6])

In [53]:
import numpy as np
np.random.seed(2)

m,n=4,3
A=np.random.randint(0,10,m*n).reshape(m,n)
b=np.random.randint(0,10,n)


In [54]:
A

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5]])

In [55]:
B

array([[4, 1],
       [7, 2]])

In [56]:
B

array([[4, 1],
       [7, 2]])

In [58]:
B=np.array([7,3,6])

In [59]:
B

array([7, 3, 6])

In [60]:
A*b

array([[56, 24, 36],
       [14, 24, 42],
       [14,  3, 30],
       [28, 12, 30]])

In [61]:
np.random.seed(3)
b=np.random.randint(0,10,n+1)

In [62]:
b

array([8, 9, 3, 8])

In [63]:
C=A*b[:,np.newaxis]

In [64]:
C

array([[64, 64, 48],
       [18, 72, 63],
       [ 6,  3, 15],
       [32, 32, 40]])

In [66]:
np.random.seed(11)

m,n=4,3
a=np.random.randint(0,10,m).reshape(-1,1)
b=np.random.randint(0,10,n)

a

array([[9],
       [0],
       [1],
       [7]])

In [67]:
b

array([1, 7, 2])

In [ ]:
a*b

...........