In [45]:
import numpy as np
A=np.random.randint(0,9,12).reshape(4,3)
B=np.random.randint(0,9,6).reshape(3,2)

C=np.dot(A,B)
C_=np.array([A[:,[j]]*B[j,0] for j in range(A.shape[1])], [A[:,[j]]*B[j,1] for j in range(A.shape[1])])
C_


TypeError: Field elements must be 2- or 3-tuples, got 'array([[12],
       [24],
       [18],
       [ 6]])'

In [28]:
C2


array([[[35],
        [30],
        [25],
        [ 5]],

       [[28],
        [12],
        [16],
        [12]],

       [[36],
        [12],
        [30],
        [12]]])

In [41]:
C11=C1.sum(axis=0)

In [32]:
C22=C2.sum(axis=0)

In [40]:
C_final=np.array([C11[i,:]for i in range(C11.shape[0]),C22[k,:] for k in range(C22.shape[0])])

SyntaxError: invalid syntax (<ipython-input-40-19af2d7ea5a1>, line 1)

In [39]:
C_final

array([[[113],
        [ 54],
        [ 77],
        [ 39]],

       [[ 99],
        [ 54],
        [ 71],
        [ 29]]])

In [35]:
np.dot(A,B)

array([[113,  99],
       [ 54,  54],
       [ 77,  71],
       [ 39,  29]])

C11

In [42]:
C11

array([[113],
       [ 54],
       [ 77],
       [ 39]])

In [46]:
import numpy as np

A=np.random.randint(0,10,12).reshape(4,3)
x=np.random.randint(0,10,3)

m=x.shape[0]
y=[]
temp=0
for i in range(A.shape[0]):
    for j in range(m):
        temp+=A[i,j]*x[j]
    y.append(temp)
    temp=0

In [47]:
 y=A.dot(x)

In [50]:
import numpy as np

A=np.random.randint(0,10,12).reshape(3,4)
x=np.random.randint(0,10,3)

m=x.shape[0]
y=[]
temp=0
for i in range(A.shape[1]):
    for j in range(m):
        temp+=A[j,i]*x[j]
    y.append(temp)
    temp=0

In [49]:
A

array([[1, 5, 4, 4],
       [2, 9, 7, 2],
       [2, 7, 2, 9]])

In [51]:
y=A.T.dot(x)

In [52]:
y

array([75, 37, 70, 64])

In [53]:
import numpy as np

np.random.seed(10)

n,m=5,2

X=np.random.rand(n,m)
w=np.random.rand(m)
y=np.random.rand(n)

X

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [54]:
w

array([0.68535982, 0.95339335])

In [55]:
y

array([0.00394827, 0.51219226, 0.81262096, 0.61252607, 0.72175532])

In [57]:
g=np.zeros_like(w)

for j in range(m):
    for i in range(n):
        g[j]+=(np.dot(X[i,:],w)-y[i])*X[i,j] 

g=np.dot(X.T,np.dot(X,w)-y)
g

In [58]:
g

array([0.65598053, 0.57259869])

In [59]:
%%timeit
for j in range(m):
    for i in range(n):
        g[j]+=(np.dot(X[i,:],w)-y[i])*X[i,j] 

26.9 µs ± 574 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [61]:
%%timeit
g=np.dot(X.T,np.dot(X,w)-y)

3.61 µs ± 26.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
