In [2]:
import numpy as np
import torch

np.random.seed(0)
x=np.random.rand(6).reshape(2,3)

x_tensor=torch.tensor(x)
x_from_numpy=torch.from_numpy(x)
x_Tensor=torch.Tensor(x)
x_as_tensor=torch.as_tensor(x)

print(x, x.dtype)

print(x_tensor, x_tensor.dtype, x_tensor.requires_grad)

print(x_from_numpy, x_from_numpy.dtype, x_from_numpy.requires_grad)

print(x_Tensor, x_Tensor.dtype, x_Tensor.requires_grad)

print(x_as_tensor, x_as_tensor.dtype, x_as_tensor.requires_grad)



[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]] float64
tensor([[0.5488, 0.7152, 0.6028],
        [0.5449, 0.4237, 0.6459]], dtype=torch.float64) torch.float64 False
tensor([[0.5488, 0.7152, 0.6028],
        [0.5449, 0.4237, 0.6459]], dtype=torch.float64) torch.float64 False
tensor([[0.5488, 0.7152, 0.6028],
        [0.5449, 0.4237, 0.6459]]) torch.float32 False
tensor([[0.5488, 0.7152, 0.6028],
        [0.5449, 0.4237, 0.6459]], dtype=torch.float64) torch.float64 False


In [3]:
x[0,0]=100

print(x, x.dtype)

[[100.           0.71518937   0.60276338]
 [  0.54488318   0.4236548    0.64589411]] float64


In [4]:
print(x_tensor, x_tensor.dtype, x_tensor.requires_grad)

tensor([[0.5488, 0.7152, 0.6028],
        [0.5449, 0.4237, 0.6459]], dtype=torch.float64) torch.float64 False


In [6]:
print(x_Tensor, x_Tensor.dtype, x_Tensor.requires_grad)

tensor([[0.5488, 0.7152, 0.6028],
        [0.5449, 0.4237, 0.6459]]) torch.float32 False


In [7]:
print(x_from_numpy, x_from_numpy.dtype, x_from_numpy.requires_grad)

tensor([[100.0000,   0.7152,   0.6028],
        [  0.5449,   0.4237,   0.6459]], dtype=torch.float64) torch.float64 False


In [8]:
print(x_as_tensor, x_as_tensor.dtype, x_as_tensor.requires_grad)

tensor([[100.0000,   0.7152,   0.6028],
        [  0.5449,   0.4237,   0.6459]], dtype=torch.float64) torch.float64 False


In [9]:
x_tensor_grad=torch.tensor(x, requires_grad=True)

print(x_tensor_grad, x_tensor_grad.dtype, x_tensor_grad.requires_grad)
                          

tensor([[100.0000,   0.7152,   0.6028],
        [  0.5449,   0.4237,   0.6459]], dtype=torch.float64,
       requires_grad=True) torch.float64 True


In [10]:
x=torch.tensor([1.0],requires_grad=True)
f= (x**2+2*x)*torch.log(x)

print(x)


tensor([1.], requires_grad=True)


In [11]:
print(f)

tensor([0.], grad_fn=<MulBackward0>)


In [12]:
print

<function print>

In [13]:
print(x.grad)

None


In [14]:
torch.autograd.backward(f, retain_graph=True)
print(x.grad)

tensor([3.])


In [16]:
df=torch.autograd.grad(f,x,retain_graph=True)
print(df)

(tensor([3.]),)


In [18]:
df=torch.autograd.grad(f, (x,x), retain_graph=True)
print(df)

(tensor([3.]), tensor([3.]))


In [20]:
x=torch.tensor([1.0], requires_grad=True)
y=torch.tensor([2.0], requires_grad=True)
f_xy=(x**2+2*x)*torch.log(y)

torch.autograd.backward(f_xy,retain_graph=True)
print(x.grad)
print(y.grad)
df=torch.autograd.grad(f_xy,(x,y), retain_graph=True)
print(df)

tensor([2.7726])
tensor([1.5000])
(tensor([2.7726]), tensor([1.5000]))
